Use the same SmsManager to divide and send a message.
signalapp/Signal-Android pull request #10137
Opened 2020-10-26 11:26 UTC by 0dvictor

### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Pixel 4 XL, Android 11
 * Virtual Device, Android 11
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/) N/A

----------

### Description

Existing implementation always use the default SmsManager to divide long message regardless the message's subscription ID, which could be problematic if any of the subscriptions' modems use a different length limit from the standard. By changing it to the correct SmsManager for the specific subscription, the issue can be resolved.

2020-12-23 07:14 UTC, Xashyar commented
@0dvictor, 
I kknow this may not be your cup of tea, but could this be related https://github.com/signalapp/Signal-Android/issues/10211?

2020-12-23 08:12 UTC, 0dvictor commented
@Xashyar I don't think so. The issue being fixed in this PR should occur only if the message need be divided into multiple. Considering the screenshot in #10211 showing that issue occurs with very short messages (e.g. 1-char message), where the message almost certainly was not divided.

2022-04-24 16:27 UTC, 0dvictor commented
@greyson-signal Could you take a look at this PR?

The current implementation uses different SmsManager to divide and send a message. This could cause issues when SmsManager divides messages differently for different subscriptions.

2022-04-25 12:42 UTC, alex-signal requested changes
Looks good, just a minor formatting issue.

2022-04-25 17:02 UTC, 0dvictor commented
Thank you @alex-signal for reviewing. I've now fixed the alignment, please take another look.

2022-04-27 20:33 UTC, cody-signal commented
Will be in 5.37

2022-04-27 20:33 UTC, closed without merging

2022-05-04 12:47 UTC, cascheberg commented
@cody-signal wrote that this change will be in 5.37, but note that 5.37.1 has been released and this change is not in there.

2022-05-04 13:55 UTC, greyson-signal commented
Bit of a mix-up with some branches, it'll be in 5.37.2, thanks for the reminder :)