Translation of display strings in Tamil is not complete Fixes #10472
signalapp/Signal-Android pull request #10473
Opened 2021-01-11 05:19 UTC by vairam-svs

Translation of display strings in Tamil is not complete Fixes #10472

### First time contributor checklist

- [ ] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [ ] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [ ] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [ ] I have tested my contribution on these devices:
 * Device A, Android X.Y.Z
 * Device B, Android Z.Y
 * Virtual device W, Android Y.Y.Z
- [ ] My contribution is fully baked and ready to be merged as is
- [ ] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

- Signal word is not "transliterated" as name in Tamil, while in other languages that show 100% in transifex is transliterated
- Are the following texts needs to stay in English:
   * Signal needs permission to your microphone and camera.
   * Signal version: 
   * Signal package: 
   * Signal settings

This is change is not 100% complete. 
Also who is the owner /contributor for Tamil Language
Also, I am unable to choose Tamil language in transifex translation to JOIN

2021-01-11 05:21 UTC, vairam-svs commented
I am submitting translation here as mentioned here https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#translations because that tool does not allows me to choose Tamil (ta) to join team even though it has translation and its an available language already

2021-01-11 06:08 UTC, Ashok314 reviewed
Language translations are not to be made an issue or a PR here. You can contribute via transifex [see here](https://github.com/signalapp/Signal-Android#contributing-translations) 

About the changes in the file,
"Signal" is not to be translated into other languages. 
FYI refer to other translations.

2021-01-11 08:02 UTC, vairam-svs commented
@Ashok314 see my comments about issues with transifex

2021-01-11 09:25 UTC, Ashok314 requested changes
see other language translations as a reference.

2021-01-11 09:25 UTC, Ashok314 commented on app/src/main/res/values-ta/strings.xml
> -  <string name="ApplicationMigrationActivity__signal_is_updating">Signal புதுப்பிக்கிறது …</string>
### Do not need to translate "Signal"
Should leave "Signal" as it is and translate others into another language. 
Same for the "Signal" appearing on other lines.

2021-01-16 06:57 UTC, Ashok314 reviewed
This PR is unnecessary/invalid and should be closed. 
Thanks.

2021-01-22 15:17 UTC, alan-signal commented
Thank you but translations are done only by our community of volunteer translators on a separate service to github. If we merged them here they would only be overwritten.

Please leave feedback on the [community forum](https://community.signalusers.org/c/translation-feedback/27). Our community of volunteer translators are able to view your suggestions, provide feedback on those independent changes, and carry over changes to our translation tools. We appreciate your help.

2021-01-22 15:17 UTC, closed without merging