Attempt to create the directory to save media files if it does not exist
signalapp/Signal-Android pull request #11511
Opened 2021-08-01 20:50 UTC by fumiakiy

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * AVD Pixel API 23
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
The current code may create an empty media in the media store if the path that [Environment.getExternalStoragePublicDirectory](https://developer.android.com/reference/android/os/Environment#getExternalStoragePublicDirectory(java.lang.String)) may returns does not exist.

The code in this PR tries a little harder to find a place to store the file before accepting a directory path that may not exist.

Fixes #11505

### Steps to verify the fix
 1. Prepare a Signal chat that has a movie file received or sent.
 2. Using `adb shell` or by any other ways, delete or rename the device's file system directory that is used for "Environment.DIRECTORY_MOVIES". In many cases this should be "/sdcard/Movies".
 3. Open Signal chat prepared at the step 1.
 4. Try to save the video file.
 5. In the chat tap on the [+] button to open the attachment keyboard.
 6. See the list of recent media files.

**Expected behavior after this PR**
The file should be saved. The directory (/sdcard/Movies) is created.

The list of recent media files has the video file that was just saved.

**Actual behavior in the current master at [429fdf0d76465e3f826c67d1334c1761cea41914]**
The file is not saved. Toast appears to tell the user something has gone wrong.

The list of recent media files has a blank (black or white) empty item in it.

2021-08-04 06:57 UTC, rrroonn commented
Just my thought, (maybe a bit late)  but it would be good  to include the failed filename (incl path) in the toast to help alleviate other potential saving issues (permissions etc).  At least in that case the user has more information to go by to work out how to fix the problem.

2021-08-04 12:17 UTC, alex-signal requested changes
Hi! Thanks for this PR.

From what I understand, this could modify where a file is saved on external storage. Could you please verify that you've tested this across a few different API levels, and ideally recreated the scenario you specified in your reproduction steps?

2021-08-04 12:17 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/util/SaveAttachmentTask.java
> +  private @Nullable String getExternalPathToFileForType(String contentType) {
Name should be updated to reflect new return type.

2021-08-04 12:17 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/util/SaveAttachmentTask.java
> +    if (storage == null || (!storage.exists() && !storage.mkdirs())) {
Consider a private method encapsulating this condition, since it's used in multiple places.

2021-08-04 12:17 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/util/SaveAttachmentTask.java
> +      }
space below

2021-08-04 12:17 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/util/SaveAttachmentTask.java
> +    if (storage == null || (!storage.exists() && !storage.mkdirs())) {
Also some spaces above and below these if blocks for readability.

2021-08-04 21:35 UTC, fumiakiy commented
Thanks for the review. I edited to respond to the review comments. Please take a look.

I also tested in a few other API levels using the same steps to verify the PR. Description is updated accordingly.

2021-08-05 13:24 UTC, alex-signal requested changes

2021-08-05 13:24 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/util/SaveAttachmentTask.java
> +    if (path.mkdirs()) return path;
Last thing (sorry!)

We've moved away from writing ifs like this, and would prefer the long form as it improves readability.

```
if (path.mkdirs()) {
  return path;
} else {
  return null;
}
```

2021-08-05 13:24 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/util/SaveAttachmentTask.java
> +    if (path.mkdirs()) return path;
(Applies to a few more areas in this code change fyi.)

2021-08-05 14:25 UTC, fumiakiy commented
Fixed the format of two `if` blocks. PTAL!

2021-08-05 14:33 UTC, alex-signal commented
Hi! Thanks very much for this. Everything looks good! I'll update here with release information as soon as I know more.

2021-08-05 16:15 UTC, Sgn-32 commented
Shouldn't be the if-condition `(path.mkdirs())` in the following form been better between the other two if-condition.

```
    if (path.mkdirs()) {
      return path;
    } else {
      path = null;
    }
```

`if (path != null && path.exists()) {`                 Best case, everything is OK
`if (path.mkdirs()) {` path don't exist, trying to create
`if (path == null) {` if creation fails the "document"-path is backup-case

2021-08-05 16:21 UTC, alex-signal commented
I'm not super keen on writing to passed parameters, and the code provided is easy to follow.

This code should go out in `5.20.1`

2021-08-05 16:21 UTC, closed without merging