Fix Signal Direct Share Shortcuts not appearing in Android Sharesheet
signalapp/Signal-Android pull request #11539
Opened 2021-08-11 21:11 UTC by nielthiart

1.  [Declare a share target](https://developer.android.com/training/sharing/receive#declare-share-target)

2.  In `org.thoughtcrime.securesms.sharing.ShareActivity`, before initiating the search/chooser interface, check for the following extra intent field and handle a direct share immediately if it is present: `EXTRA_SHORTCUT_ID`.

    Since a direct share action does not include intent as originally added when building the dynamic shortcut, we need to find the shortcut and get extra fields (threadId, distributionType) from the shortcut.

3.  If direct share fails, show search/chooser UI as before.

### First time contributor checklist

- [x I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * LM-G710EM, Android 10
 * Virtual device Nexus 5X, Android 11
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

Signal does not show up on Android Sharesheet, because it:
1. does not declare a [share target](https://developer.android.com/training/sharing/receive#declare-share-target),
2. does not handle androidx.core.content.pm.ShortcutManagerCompat.EXTRA_SHORTCUT_ID at all, and
3. relies on the original shortcut intent when it isn't present on direct share.

This pull request intends to fix these three issues.

2021-08-12 08:43 UTC, nielthiart commented on app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java
> +    boolean intentHasRecipient = getIntent().hasExtra(EXTRA_RECIPIENT_ID);
This check for `getIntent().hasExtra(EXTRA_RECIPIENT_ID)` might not be necessary, I couldn't find a valid path to get to this activity with this extra field set.

Android `ACTION_SEND` and `ACTION_SEND_MULTIPLE` only include on extra field we can use: `ShortcutManagerCompat.EXTRA_SHORTCUT_ID`

2021-08-12 08:51 UTC, nielthiart commented
I refactored my first change to app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java to rather update only the `initializeIntent` method without changing any other existing methods.

Per Android docs [Receiving simple data from other apps](https://developer.android.com/training/sharing/receive#declare-share-target), Direct Share intent does not include the intent and extras we declared when adding dynamic shortcuts, we only get `EXTRA_SHORTCUT_ID`, which in Signal should be a 'recipientId'.

My last commit includes a fallback to create intent incase the shortcuts have changed before we handle direct share.

Fixes #11537

2021-08-12 18:16 UTC, alex-signal requested changes
Thanks for fixing this! A few review comments but looks pretty good otherwise.

2021-08-12 18:16 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java
> +    boolean intentHasRecipient = getIntent().hasExtra(EXTRA_RECIPIENT_ID);
Align `=`

2021-08-12 18:16 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java
> +      Bundle shortcutExtras = getShortcutExtrasFor(extraShortcutId);
align `=`

2021-08-12 18:16 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java
> +    boolean intentHasRecipient = getIntent().hasExtra(EXTRA_RECIPIENT_ID);
There might be a path via the media preview activity's forward action. We are moving away from using ShareActivity for internal message forwarding from ConversationActivity.

2021-08-12 18:16 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java
> +        // In case the shortcut no longer exists, fallback to creating intent
No need to leave comments around like this :)

2021-08-12 18:16 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java
> +    for (int a = 0, N = shortcuts.size(); a < N; a++) {
This pattern isn't really used elsewhere in the app. Also, I believe you could just use a for-each loop here:

```
for (ShortcutInfoCompat shortcut : shortcuts) { ... }
```

2021-08-12 22:02 UTC, nielthiart commented on app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java
> +        // In case the shortcut no longer exists, fallback to creating intent
Thanks, updated in 559ef6a997ee73888812d36f7d7f145fb7597874

2021-08-12 22:02 UTC, nielthiart commented on app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java
> +      Bundle shortcutExtras = getShortcutExtrasFor(extraShortcutId);
Thanks, updated in 559ef6a997ee73888812d36f7d7f145fb7597874

2021-08-12 22:03 UTC, nielthiart commented on app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java
> +    for (int a = 0, N = shortcuts.size(); a < N; a++) {
This is so much simpler, thanks! Fixed in 39d5db1a9e6dd6ab0549b2cd6a2b144ee06c9836

2021-08-12 22:04 UTC, nielthiart commented on app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java
> +    boolean intentHasRecipient = getIntent().hasExtra(EXTRA_RECIPIENT_ID);
Aligned in 559ef6a997ee73888812d36f7d7f145fb7597874

2021-08-13 07:38 UTC, nielthiart commented
Alex, thanks so much for the review. I don't write Java regularly, so if you have any other concerns about this pull request, please don't feel bad to point them out or change it completely - however trivial or big the feedback/change.

I guess there is some opportunity to encapsulate the direct share logic in its own class at some point, but I tried to keep this fix as small and simple as possible.

I've been using this branch for a few days on Android 10, and sharing screenshots/images with regular contacts really is much easier now.

Assumptions I made when responding to your previous requests:

- We don't need comments that only repeat what the method name implies.
- Assignments in different but adjacent code blocks have their own alignment, for example the variable names and `=` in these lines: https://github.com/signalapp/Signal-Android/blob/559ef6a997ee73888812d36f7d7f145fb7597874/app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java#L255-L260
- Since these are small requests, I marked them as resolved - not sure about the preferred workflow there.

Thanks again!

2021-08-13 12:19 UTC, alex-signal requested changes
No problem :) I realize that Signal has some oddities when it comes to how we format our code. There's just one issue now, since it appears the code changes will access the database on the main thread, which we cannot do (since it can slow down the user experience, cause ANRs, and is generally just not a good practice).

2021-08-13 12:19 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java
> +  @Nullable private Bundle getShortcutExtrasFor(@NonNull String extraShortcutId) {
Signal style is:

```
<override annotation>
<access modifier> <nullability annotation> <return type> <method name>(<params>) { ...
```

So this should be adjusted to `private @Nullable Bundle`

2021-08-13 12:19 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java
> +      threadId = DatabaseFactory.getThreadDatabase(this).getThreadIdFor(recipientId);
This is an issue. We shouldn't ever access the database (or do any other sort of IO) on the main thread.

Proposed solution here is to use `SimpleTask`:

```
SimpleTask.run(
    getLifecycle(), 
    () -> DatabaseFactory.getThreadDatabase(this).getThreadIdFor(recipientId), 
    threadId -> { ... }
)    
```

This may have other implications as well. I believe it means that `handleDestination` will need to be invoked in the 3rd argument (foreground task) of the `SimpleTask`, instead of in `onCreate` (in the case of this method being invoked).

There's then an argument for UI treatment since we're offloading work, but it should return fast enough that it shouldn't make a difference. We're just very antsy about anything that could cause an ANR (like accessing a database from the main thread)

2021-08-13 13:30 UTC, nielthiart commented on app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java
> +      threadId = DatabaseFactory.getThreadDatabase(this).getThreadIdFor(recipientId);
Thanks, moving IO off the main thread makes complete sense. I'd like to fix this.

1. Should I move IO off the main thread first and then treat fixing the UI as a completely separate issue (outside this pull request)?
2. Does the call to Android's `ShortcutManagerCompat.getDynamicShortcuts()` in `getShortcutExtrasFor` not also potentially block on the main thread?

Regarding UI - at the moment we initialize search before `handleDestination`, so there is already a flash of the search UI before we call `ConversationActivity`, which flashes the conversation view, before we call `MediaSendActivity`. I initially checked for direct share first, before falling back to search if necessary, but in the end I decided to keep my update small because I'm not that familiar with the codebase.

2021-08-13 13:34 UTC, nielthiart commented on app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java
> +  @Nullable private Bundle getShortcutExtrasFor(@NonNull String extraShortcutId) {
Thanks, fixed in https://github.com/signalapp/Signal-Android/pull/11539/commits/2d0ac4f4ddfd1fd2610cc5be80c98f7c88996f80

2021-08-13 13:37 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java
> +      threadId = DatabaseFactory.getThreadDatabase(this).getThreadIdFor(recipientId);
> Does the call to Android's ShortcutManagerCompat.getDynamicShortcuts() in getShortcutExtrasFor not also potentially block on the main thread?

It should be done off-thread as well, yeah. Good catch!

> Should I move IO off the main thread first and then treat fixing the UI as a completely separate issue (outside this pull request)?

Let's not worry about UI, and focus on getting these calls off the main thread.

2021-08-13 19:08 UTC, nielthiart commented on app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java
> +      threadId = DatabaseFactory.getThreadDatabase(this).getThreadIdFor(recipientId);
Blocking call handling updated in https://github.com/signalapp/Signal-Android/pull/11539/commits/a6a57e0de87785165e5bf5b9dc86c5c556bcef43

I moved all Direct Share handling to a dedicated method, and call this in onResume so that we have lifecycle for SimpleTask.

handleDestination is only called when the necessary intent is present, so has been simplified.

I tested these changes on Android 10 only, but I haven't included any new external calls.

I'm not sure I'm going in the right direction with this, feedback welcomed. Thanks for the patience and hints here.

2021-08-16 13:40 UTC, alex-signal requested changes
A few annotations I'd like added just to call these methods out, then it should be all good.

2021-08-16 13:40 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java
> +  private @Nullable Bundle createExtrasFromExtraShortcutId(@NonNull String extraShortcutId) {
```suggestion
  @WorkerThread
  private @Nullable Bundle createExtrasFromExtraShortcutId(@NonNull String extraShortcutId) {
```

2021-08-16 13:40 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java
> +  private @Nullable Bundle getDirectShareExtras(@NonNull String extraShortcutId) {
```suggestion
  @WorkerThread
  private @Nullable Bundle getDirectShareExtras(@NonNull String extraShortcutId) {
```

2021-08-16 13:40 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java
> +  private @Nullable Bundle getShortcutExtrasFor(@NonNull String extraShortcutId) {
```suggestion
  @WorkerThread
  private @Nullable Bundle getShortcutExtrasFor(@NonNull String extraShortcutId) {
```

2021-08-16 13:41 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/sharing/ShareActivity.java
> +      threadId = DatabaseFactory.getThreadDatabase(this).getThreadIdFor(recipientId);
> I'm not sure I'm going in the right direction with this, feedback welcomed. Thanks for the patience and hints here.

If we want to get technical and proper, this call would get routed through the view model to a repository. However, this particular activity already has calls elsewhere that do offthread work from within this class, and I'd really rather get it in and into the hands of users (because it's an important change) rather than bikeshed :)

2021-08-16 13:59 UTC, nielthiart commented
Thanks for the reviews and your help in getting this done.

2021-08-16 14:02 UTC, alex-signal commented
![Thank you!](https://media.giphy.com/media/4BylJD2QxStzO/giphy.gif)

Thanks for sticking through it! This should go out in a build soon.

2021-08-16 16:29 UTC, alex-signal commented
This will go out in 5.21.2

2021-08-16 16:29 UTC, closed without merging