Fixes #11547 Update exoplayer v2.15.0
signalapp/Signal-Android pull request #11562
Opened 2021-08-22 20:03 UTC by makp9k

Fixes #11547

### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Sony Xperia XZ1, Android 9
 * OnePlus 7, Android 11
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

This PR fixes an issue when VoiceNotePlaybackService loses its foreground state right after the playback starts, allowing the system to kill the service, which results in audio being interrupted. The changes are coming partly from the updated ExoPlayer (see https://github.com/google/ExoPlayer/issues/4988), so I decided to pick the latest version at the moment, which might become handy in further development.

2021-08-23 12:57 UTC, alex-signal requested changes
Wow! Thanks for doing this! Most of my code feedback is around code style and alignment.

We utilize ExoPlayer in a few different places, so it's important that all these paths are tested:

* Gif search
* Gif playback inside the conversation
* Gif playback after clicking a gif in the conversation
* Video playback throughout the app
* Video editing I *think*
* Sending a video (has some stuff around thumbnail generation, don't remember if this hits exo)

Also can you confirm that the playback speed and proximity sensor still functions as expected? (I see necessary changes to the dispatcher due to API changes)

2021-08-23 12:57 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/components/voice/VoiceNoteMediaController.java
> +    return mediaMetadataCompat != null &&
Alignment: In Signal Java, we align &&'s

2021-08-23 12:57 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/video/VideoPlayer.java
> +        @Override public void onPlayWhenReadyChanged(boolean playWhenReady, int reason) {
For throughout the PR: Override should go on a separate line above signature.

2021-08-23 12:57 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/video/VideoPlayer.java
> +        .createMediaSource(MediaItem.fromUri(videoSource.getUri()));
Align `.`s

2021-08-23 12:57 UTC, alex-signal commented on gradle/wrapper/gradle-wrapper.properties
> -distributionSha256Sum=22449f5231796abd892c98b2a07c9ceebe4688d192cd2d6763f8e3bf8acbedeb
We'll want to revert this file's changes.

2021-08-23 13:07 UTC, makp9k commented on gradle/wrapper/gradle-wrapper.properties
> -distributionSha256Sum=22449f5231796abd892c98b2a07c9ceebe4688d192cd2d6763f8e3bf8acbedeb
My bad, I had no plans to include this in the PR :)

2021-08-23 13:09 UTC, makp9k commented
Thank you for the review! I will check the points above and will update my PR accordingly.
Playback speed and proximity sensor were working on the devices I tested the app with.

2021-08-23 18:30 UTC, makp9k commented on app/src/main/java/org/thoughtcrime/securesms/components/voice/VoiceNoteMediaController.java
> +    return mediaMetadataCompat != null &&
This was already like this, didn't touch it, but will format properly.

2021-08-25 12:05 UTC, alex-signal requested changes
Hi! This is starting to look good. Mostly formatting changes and a few questions for my own edification. We do not use Jetbrains's nullability annotations, opting for Android's instead.

2021-08-25 12:05 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/conversation/ConversationItem.java
> +import static org.thoughtcrime.securesms.util.ThemeUtil.isDarkTheme;
We avoid static imports.

2021-08-25 12:05 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/conversation/ConversationUpdateItem.java
>    public ConversationMessage getConversationMessage() {
The pattern we use is:

```
<override annotation>
<access modifier> <nullability annotation> <return value> <method name>(<args>) {
```
```

2021-08-25 12:05 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/conversation/ConversationUpdateItem.java
> +import org.jetbrains.annotations.NotNull;
Wrong nullability annotation, as noted previously :)

2021-08-25 12:05 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/giph/mp4/GiphyMp4ExoPlayerProvider.java
> +  private final OkHttpClient okHttpClient = ApplicationDependencies.getOkHttpClient().newBuilder().proxySelector(new ContentProxySelector()).build();
alignment

2021-08-25 12:05 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/giph/mp4/GiphyMp4ExoPlayerProvider.java
> +    this.context = context;
alignment

2021-08-25 12:05 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/giph/mp4/GiphyMp4ExoPlayerProvider.java
> +    SimpleExoPlayer exoPlayer = new SimpleExoPlayer.Builder(context)
This `.` alignment is perfect :)

2021-08-25 12:05 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/giph/mp4/GiphyMp4ProjectionPlayerHolder.java
> +import org.jetbrains.annotations.NotNull;
Wrong nullability annotation. If you want, there is a setting in AS that lets you choose a default nullability annotation.

2021-08-25 12:05 UTC, alex-signal commented on app/build.gradle
> +    implementation 'androidx.media:media:1.4.1'
Is this a new requirement from exoplayer, or just for the Media Compat stuff? I'm surprised we didn't have this already.

2021-08-31 08:15 UTC, makp9k commented
@alex-signal please let me know if i can further improve it

2021-08-31 12:30 UTC, alex-signal commented
Hi! Last ask, please run `./gradlew ktlintformat` :)

2021-08-31 12:52 UTC, makp9k commented
Done :)

2021-09-01 12:14 UTC, alex-signal commented
Thanks! I'll see to this getting merged in and let you know if we need anything else.

2021-09-01 14:30 UTC, alex-signal requested changes
A few formatting changes, and there are also test failures. It's possible the tests failing are no longer relevant, and as such I'd ask they'd be removed. You can run tests on the command line via `./gradlew qa` or with normal command line gradle test commands for the `signal-android` module.

2021-09-01 14:30 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/components/voice/VoiceNoteNotificationManager.java
> +    notificationManager = new PlayerNotificationManager.Builder(
formatting

2021-09-01 14:30 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/components/voice/VoiceNotePlaybackPreparer.java
> +                       ThreadUtil.postToMain(() -> Toast
This is a situation where the alignment actually increases confusion. Should wrap this in braces and indent it.

2021-09-01 14:30 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/components/voice/VoiceNotePlaybackPreparer.java
> +      if (playbackProperties != null && playbackProperties.uri.equals(uri)) return i;
Avoid same-line if where possible

2021-09-01 19:50 UTC, makp9k commented on app/src/main/java/org/thoughtcrime/securesms/components/voice/VoiceNoteNotificationManager.java
> +    notificationManager = new PlayerNotificationManager.Builder(
Fixed

2021-09-01 19:50 UTC, makp9k commented on app/src/main/java/org/thoughtcrime/securesms/components/voice/VoiceNotePlaybackPreparer.java
> +      if (playbackProperties != null && playbackProperties.uri.equals(uri)) return i;
Fixed

2021-09-01 19:52 UTC, makp9k commented
Thank you for your time, Alex! I've adjusted the PR :)

2021-09-02 12:10 UTC, alex-signal commented
![Thank you!](https://media.giphy.com/media/4BylJD2QxStzO/giphy.gif)

This should go out in `5.23`

2021-09-02 12:10 UTC, closed without merging