Contact share UI #8081
signalapp/Signal-Android pull request #11616
Opened 2021-09-14 08:57 UTC by Cerenia

### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Xiaomi Redmi 9T, Android 10 QKQ1.200830.002
 * Virtual Pixel 3a API 30
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

When sharing a contact, the check boxes which control what information is to be shared were not reactive to the whole line.
This is fixed by holding a reference to the parent view and adding an onClickListener to toggle the checkbox when the parent is clicked. 

Tested by creating a contact with many phone numbers, necessitating scrolling, and checking that the checkboxes still behave as expected and retain state when coming in and out of view.

2021-09-21 12:36 UTC, alex-signal commented
Hi! Since this is a UI change, can you please include screenshots? You can blur out any sensitive information.

2021-09-21 12:38 UTC, alex-signal requested changes

2021-09-21 12:38 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/contactshare/ContactFieldAdapter.java
> +    private View parent;
There's no need to hold an explicit reference to parent, since the super class exposes itemView as a public field.

2021-09-21 12:38 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/contactshare/ContactFieldAdapter.java
> +        parent.setOnClickListener(new android.view.View.OnClickListener() {
You can use lambda syntax here instead of creating an anonymous object.

2021-09-21 14:33 UTC, Cerenia commented
> 
> 
> Hi! Since this is a UI change, can you please include screenshots? You can blur out any sensitive information.

Hi Alex,
Thanks for the review, the requested simplifications have been applied and a screenshot added. The change is purely behavioral though, so it does not show anything visually different than it is in the current UI.

2021-09-21 20:45 UTC, Tursko commented
Referenced issue https://github.com/signalapp/Signal-Android/issues/8081

2021-09-23 12:05 UTC, alex-signal commented
Hi! this is on target to go into 5.25. Thanks for your pull request!

2021-09-23 12:05 UTC, closed without merging