Close okhttp response body for all storage requests and for unsuccessful requests
signalapp/Signal-Android pull request #11745
Opened 2021-11-08 21:14 UTC by AsamK

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * OnePlus 8T, Android 11
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
OkHttp response bodies need to be closed to not leak resources.
In PushServiceSocket.java some code paths didn't close the body:
- some storage requests that ignored the response body also didn't close it
- In `makeServiceRequest` and `makeStorageRequestResponse` the body wasn't closed for unsuccessful requests

I fixed the unsuccessful requests by adding a catch and rethrow the exception after closing the body. Maybe there's a nicer solution for that ...

2021-11-09 13:21 UTC, alex-signal requested changes
Thanks for your PR! I think we're better off using try-with-resources if we are able to.

2021-11-09 13:21 UTC, alex-signal commented on libsignal/service/src/main/java/org/whispersystems/signalservice/internal/push/PushServiceSocket.java
> +      ResponseBody response = makeStorageRequest(authToken, "/v1/storage", "PUT", protobufRequestBody(writeOperation));
Alternatively, could we use try-with-resources here?

```
try (ResponseBody response = makeStorageRequest(...)) {
}
```

That would ensure that the body is closed since it implements closeable.

2021-11-09 13:21 UTC, alex-signal commented on libsignal/service/src/main/java/org/whispersystems/signalservice/internal/push/PushServiceSocket.java
> +      responseCodeHandler.handle(response.code(), responseBody);
Same comment, let's prefer try-with-resources wherever we can.

2021-11-09 14:02 UTC, AsamK commented
Thanks for reviewing @alex-signal . I've changed the code as requested.
I didn't use try with resource at first because of the empty try block ... but it's probably better this way :)

2021-11-09 15:20 UTC, AsamK commented on libsignal/service/src/main/java/org/whispersystems/signalservice/internal/push/PushServiceSocket.java
> +      responseCodeHandler.handle(response.code(), responseBody);
ah, actually here we can't use try-with-resources, as the body should only be closed if an exception is thrown, and not in the success case.

2021-11-09 15:28 UTC, alex-signal commented on libsignal/service/src/main/java/org/whispersystems/signalservice/internal/push/PushServiceSocket.java
> +      responseCodeHandler.handle(response.code(), responseBody);
Got it, ok. Let's then just make sure it's closed where it makes sense to be in these cases, and verify calling code (whomever is being passed the resource) also closes things (and ignore me if you already did)

2021-11-09 15:41 UTC, alex-signal commented
@AsamK Sorry to be a pain, we discussed it and would prefer instead of an empty response, to implement a method specifically for ignored responses:

`makeAndCloseStorageRequest`

Which takes the same arguments that `makeStorageRequest` takes but also immediately cleans up the response object if it's present.

Furthermore, it was decided that empty try blocks don't read as nice as a simple if != null check, so let's do that instead :)

2021-11-09 16:09 UTC, AsamK commented
Alright I've pushed the changes @alex-signal . With a separate `makeAndCloseStorageRequest` it's indeed nicer.
I checked the methods using the response body in the success case and found just one method that didn't close the body: `getGroupsV2GroupHistory`
The other places all call either `.string()` or `.bytes()` which implicitly close the body.

2021-11-10 16:39 UTC, AsamK commented
I found two more places, one in `getMessages` and another in the `submitServiceRequest` method that returns a `ListenableFuture`. I've pushed an additional commit.

2021-11-11 17:23 UTC, alex-signal commented
This is going out in `5.27` (baring any glaring issues that pop up)

Thanks very much for your PR!

2021-11-11 17:23 UTC, closed without merging