Do not allow forwarding a link preview when its image is not downloaded yet
signalapp/Signal-Android pull request #11891
Opened 2022-01-09 22:11 UTC by fumiakiy

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Samsung Galaxy S6, Android 7
 * AVD Pixel 4, API 30
- [x] My contribution is fully baked and ready to be merged as is
- [ ] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
Link preview can have images and those images can be pending download depending on the media settings. Images and movies cannot be forwarded before they are downloaded but forwarding button is available on the toolbar if you select a link preview whose image is not downloaded yet. But forwarding ultimately fails if the image was not available yet, making the behavior looks confusing to users.

The solution implemented in this PR is to set hasPendingMedia for link previews so that actions that should not be available would not become available.

The bug was [reported in the beta forum by Blue42](https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-27-release/38993/202).

### Screen recordings

**bug**

https://user-images.githubusercontent.com/28482/148703023-90d7b055-ee3c-4ec8-b1cc-71fb54e1d6b5.mp4

**fixed**

https://user-images.githubusercontent.com/28482/148703045-531372d6-b2a3-4845-a400-d51c0181859d.mp4

2022-01-10 13:44 UTC, teynav commented
Won't it better to still allow forwarding link previews but if image is not downloaded then download it first?

2022-01-10 14:01 UTC, fumiakiy commented
> Won't it better to still allow forwarding link previews but if image is not downloaded then download it first?

Could be. But it would become a new feature because Signal doesn't behave that way when forwarding other media.

2022-03-12 23:12 UTC, fumiakiy commented
Yes it's still relevant.

2022-03-14 14:42 UTC, greyson-signal requested changes

2022-03-14 14:42 UTC, greyson-signal commented on app/src/main/java/org/thoughtcrime/securesms/mms/Slide.java
> +  public @NonNull String getContentDescription(@NonNull Context context) { return ""; }
Seems like this (and resulting changes to subclass) is a separate thing that doesn't need to be in this PR.

2022-03-14 17:33 UTC, fumiakiy commented on app/src/main/java/org/thoughtcrime/securesms/mms/Slide.java
> +  public @NonNull String getContentDescription(@NonNull Context context) { return ""; }
It's necessary to not require `Context` in Slide constructor to make [this line](https://github.com/signalapp/Signal-Android/pull/11891/files#diff-3da0cade0ad78366f5959ea36324f43bca9614878e47ff5a932fa13cd068d995R78) possible there.

I could remove the `@Nullable Context context` parameter in the constructor altogether but I didn"t because I thought it would make this PR look doing something that is not absolutely necessary for the PR to be self contained.

2022-07-06 15:21 UTC, closed without merging