Make backup folder changeable
signalapp/Signal-Android pull request #12154
Opened 2022-04-12 16:05 UTC by Roghetti

### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Virtual Device, Android 11
 * Virtual Device, Android 12
 * Virtual Device, Android 12.1
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

When you enable backups, you can choose a backup folder (since Android 10). You also get a freshly generated passphrase. But when you want to change your backup folder, currently you have to turn backups off and on again. There is no other way to choose a different folder. This comes with the downside that you also get a new passphrase. This Pull Request makes the displayed folder name clickable so you can choose another backup folder. Not moving or removing the current backup can be seen as a feature, the user keeps the copy of the backup (probably on another storage device). The user can move or remove the old backup files manually.

2022-04-27 20:41 UTC, cody-signal requested changes
Given the size backups can grow to, I don't think we consider leaving it in the old directory as a feature. Please update the PR to warn the user and remove the backups before switching, or move them to the new location as they are technically still valid.

Additionally if you could see if we can release our permission claims on the old directory so we don't hold onto access we no longer need that would be great too (if you aren't already).

2022-05-02 09:42 UTC, Roghetti commented
Sure, I can move the old backups to the new location.

Removing the permission for the old backup folder is a good idea, I’ll see if that’s possible and do that if it is.

Could you have a look at my other Pull Request (https://github.com/signalapp/Signal-Android/pull/11900) again, which is about chunking backups. This is even more pressing for us. With this PR (12154) alone, we would be able to switch online to a backup folder to SD cards, but it wouldn’t help us a lot, as it doesn’t allow files > 4GB.

Thank you :)

2022-11-06 01:31 UTC, Goldmaster commented
This looks very useful and nice to see. The backups feature needs to be severely improved on. There's nothing worse than losing chat history.

2022-11-07 15:03 UTC, cody-signal commented
It's something we're tracking internally, but I'm not sure when we'll get back to this. In a dire emergency, you can technically change the directory by disabling backups and re-enabling it and picking a new directory. This has the additional unfortunate impact of making a new passphrase so make sure to record it if you do this.

2023-01-13 22:10 UTC, closed without merging

2023-05-19 06:04 UTC, olof-nord commented
This is something which I would love to see as well. My backup file is growing in size and now I do not have enough space on my device left.

2023-06-11 08:05 UTC, Goldmaster commented
Can this be reopened, please?

2023-08-28 20:12 UTC, navid-zamani commented
A simple solution from the wise old men of Unix is, to just make the directory that Signal backs up to a softlink to somewhere else.

E.g. via `adb shell` just go
```lang-sh
cd /sdcard
mv Signal MyNewPath
ln -s MyNewPath Signal
```

At least if Google isn’t doing some of its psychopathic shenenigans again. (In that case: Go back to being a person: Get root. :)

2023-11-12 01:04 UTC, Keisial commented
I detected this missing functionality and I am glad someone had actually coded it, @Roghetti!

Looking at the PR, it seems quite straightforward, but I have a couple of comments:

It moves the old backups by doing a copy+delete. While I'm not an android developer... isn't there a rename() that could be done? A copy+delete fallback might still be needed (e.g. old or new folder is on sdcard but the other isn't) but if both folders are on the same filesystem, a real rename() would be the right primitive.

It also seems that you call a onPartialSuccess() callback if some backups moved and others didn't, but it is not used (e.g. to show a message to the user saying that not all backups moved and they will need to move them manually)

2024-04-19 17:30 UTC, lp35 commented
> It's something we're tracking internally, but I'm not sure when we'll get back to this. In a dire emergency, you can technically change the directory by disabling backups and re-enabling it and picking a new directory. This has the additional unfortunate impact of making a new passphrase so make sure to record it if you do this.

Backup is one of the most important things for an app like Signal. The workaround is NOT reliable at all, and FORCE the user to change and backup its passphrase for every backup file. Do you have any news on the internal tracking of this request?

@Roghetti gave its spare time to improve this functionnality. I personnaly backup signal over Webdav using Davx5, and sometime I need to remove the mount and make it again. Signal is not able to reuse the same folder after that. This feature is a MUST HAVE for any proper backup.

Thanks for any effort you can put on this.

Regards!

2024-04-19 19:49 UTC, UserX404 commented
Sure Webdav isn't Nextcloud exclusive, but if you'r running a NC you could use NC-App with auto upload of custom folder. I'm running this setup for several years now. Actually the team is enhancing/expanding backup functionality, so fingers crossed that also your issue get some love. ;-)

2024-04-19 21:14 UTC, lp35 commented
> Sure Webdav isn't Nextcloud exclusive, but if you'r running a NC you could use NC-App with auto upload of custom folder. I'm running this setup for several years now. Actually the team is enhancing/expanding backup functionality, so fingers crossed that also your issue get some love. ;-)

That's great news thanks! Don't want to spoil the world with the new features, but will you offer a solution for self-hosted infras? 

Regards

2024-04-20 01:28 UTC, navid-zamani commented
Everyone, please remember that all of this is just very ugly hacks that should never be allowed to exist in the first place.

The correct, sane solution for a Unix-like operating system, which Android/Linux and iOS/BSD are under the hood, is to make a copy of the files that Signal uses. Not have each app implement its own backup system. That is already insanity.  
You either make a snapshot of the file system or do it directly, but in any case, merely copy the files of Signal to a safe place, which is just a basic `cp -a` called from a trigger of your choice (like a cron job equivalent). While Signal has closed all files (aka is temporarily stopped) of course.

If you do not own/control your pocket computer (aka smartphone), as is the case with most smartphones by default and the whole point of the iPhone, then the owner decides, and you *chose* that, so boo hoo, how about: you become a person?!

In any case, both Android and iOS got built-in backup facilities. It’s just that the only backup provider they have built in is “the cloud”. Aka date hostage taking. Something at least the EU will probably soon change.

If you already have gone off the deep end, to complete looney land of pants-on-head insanity, and want to operate within the realms of that prison, then it’s a *bit* imprudent to then demand that some free app should enable your continued self-enslavement.  
If you can apparently demand things so loudly, then go to your government and tell them you want a law that hands out 20 years of prison for lock-in schemes or whatever, and replace them if they do not comply, instead of this. You know… like a *person*.

For what it’s worth,  
if you are not free to do any of this currently, but will at the first chance, then of course there is another temporary solution until then, as it is still a Unixy OS:  
Make a softlink or bind mount to a mounted FUSE file system that internally does whatever pleases you. sshfs to a backup server, with a local cache, you name it.  
On Android, there’s an insane re-implementation of that, called Storage Access Framework, and many things can offer SAF shares to other apps. Termux for example. You can even run a full virtual Linux in a virtual container, and offer SAF to that. Or run adb or sshfs to much of the local and external file systems.

**I know, freedom scares the imprisoned mind, but the point is, that the principles are simple and emergent and you got the choice.  Everything is a file. A backup is just a copy. *Zero re-implementation of the wheel needed*.**

The idea of running Signal on a device that you don’t even have root to, but a hostile enemy (Google/Apple/…) does, is the pinnacle.of insanity anyway. Every OTA update of Android can do everything to make all the security of Signal pointless. It likely already is.

Maybe next time get a Fairphone…

You may.pitchfork me now.

— Consider me your *Oxymoinsdanus*, destroyer of bullshit. 😁