Fix URL trailing symbols
signalapp/Signal-Android pull request #12309
Opened 2022-06-23 23:18 UTC by ylpoonlg

### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Samsung A9000, Android 6.0.1
 * Samsung A9200, Android 10
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

Fixes #10898, fixes #11310.
Includes trailing punctuation to the URLSpan of messageBody.
It looks for the first illegal url character after the original span and extend the span so that anything in between is included.

(Reopened #12308 with different branch.)

2022-06-24 12:18 UTC, alex-signal requested changes

2022-06-24 12:18 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/conversation/ConversationItem.java
> +          URLSpan newSpan = new URLSpan(messageBody.toString().substring(start, newEnd));
formatting:

```
int     newEnd  =
URLSpan newSpan =
```

2022-06-24 12:18 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/conversation/ConversationItem.java
> +        int     end   = messageBody.getSpanEnd(urlSpan);
Formatting

```
int start = 
int end   =
```

2022-06-24 12:18 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/conversation/ConversationItem.java
> +      URLSpan[] urlSpans = messageBody.getSpans(0, messageBody.length(), URLSpan.class);
Definitely *not* something you need to do in this PR but this linkifying logic feels like a great candidate for a set of unit tests.

2022-06-27 12:24 UTC, alex-signal commented
This is looking good! For my own education, and use in Unit tests (that I'll hopefully write once this is pulled in) could you add a few examples of URLs that were previously broken that this change fixes? (Just in a github comment, no need to do so in code)

2022-06-27 12:51 UTC, ylpoonlg commented
[https://fr.ulule.com/sapins-barbus-la-bd-/](https://fr.ulule.com/sapins-barbus-la-bd-/)
[https://www.instagram.com/tv/CfImYdngccQ/?igshid=YmMyMTA2M2Y=](https://www.instagram.com/tv/CfImYdngccQ/?igshid=YmMyMTA2M2Y=)

Apparently, the problem only exist when there is a symbol (e.g. .,/+-=?) at the end followed by a space or a newline character.

2022-06-27 13:27 UTC, alex-signal commented
thanks! I've added these as test cases.

2022-06-27 13:40 UTC, alex-signal approved these changes

2022-06-29 19:46 UTC, closed without merging