UI: Rich Text Can be Pasted into a Signal Message #8058
signalapp/Signal-Android pull request #12614
Opened 2022-11-17 16:08 UTC by gitstart

### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Techno LD7 Android 10
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

Removes formatting from pasted text whilst preserving any mentions

To test : 
1. Copy rich text with various formatting eg from [here](https://github.com/signalapp/Signal-Android/blob/main/CONTRIBUTING.md).
2. Paste it into the message box and note that it won't have the formatting.

### Videos
Issue
https://www.loom.com/share/e3d98b95b6f246768970051d2d0ae431

Fix 
https://www.loom.com/share/38ca580d3ecd47899062f02ce901660d

2022-11-18 14:49 UTC, alex-signal requested changes
A bunch of formatting stuff.

2022-11-18 14:49 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/components/emoji/EmojiEditText.java
> +              .getSystemService(Context.CLIPBOARD_SERVICE));
this can just go on the preceeding line

2022-11-18 14:49 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/components/emoji/EmojiEditText.java
> +      if (textToPaste == null) return super.onTextContextMenuItem(id);
Please use braces :-)

2022-11-18 14:49 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/components/emoji/EmojiEditText.java
> +      CharSequence     sanitizedText    = (textToPaste instanceof Spanned) ?
```
condition ? if_true
          : if_false
```

2022-11-18 14:49 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/components/emoji/EmojiEditText.java
> +      boolean           retVal          = super.onTextContextMenuItem(id);
No formatting needed here.

2022-11-18 14:49 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/components/emoji/EmojiEditText.java
> +    return data == null || data.getItemCount() == 0 ? null
Align ? and :

2022-11-22 06:41 UTC, gitstart commented on app/src/main/java/org/thoughtcrime/securesms/components/emoji/EmojiEditText.java
> +              .getSystemService(Context.CLIPBOARD_SERVICE));
@alex-signal 
Acknowledged.

2022-11-22 06:41 UTC, gitstart commented on app/src/main/java/org/thoughtcrime/securesms/components/emoji/EmojiEditText.java
> +      if (textToPaste == null) return super.onTextContextMenuItem(id);
@alex-signal 
Acknowledged.

2022-11-22 06:41 UTC, gitstart commented on app/src/main/java/org/thoughtcrime/securesms/components/emoji/EmojiEditText.java
> +      CharSequence     sanitizedText    = (textToPaste instanceof Spanned) ?
@alex-signal 
Acknowledged.

2022-11-22 06:41 UTC, gitstart commented on app/src/main/java/org/thoughtcrime/securesms/components/emoji/EmojiEditText.java
> +      boolean           retVal          = super.onTextContextMenuItem(id);
@alex-signal 
Acknowledged.

2022-11-22 06:41 UTC, gitstart commented on app/src/main/java/org/thoughtcrime/securesms/components/emoji/EmojiEditText.java
> +    List<Mention>                 mentions = MentionAnnotation.getMentionsFromAnnotations(text);
@alex-signal 
Acknowledged.

2022-11-22 06:45 UTC, gitstart commented on app/src/main/java/org/thoughtcrime/securesms/components/emoji/EmojiEditText.java
> +    return data == null || data.getItemCount() == 0 ? null
@alex-signal
Acknowledged.

2022-11-22 06:45 UTC, gitstart commented
@alex-signal 
Please check now. All the changes are pushed.
Thank you!

2022-11-22 14:42 UTC, greyson-signal approved these changes
Hi there, this will go out in 6.4. Thanks!

2022-11-28 17:36 UTC, gitstart commented
> Hi there, this will go out in 6.4. Thanks!

Thank you @greyson-signal..

2022-12-01 01:17 UTC, closed without merging