Make it clear that payment notes have limited length
signalapp/Signal-Android pull request #12616
Opened 2022-11-17 21:40 UTC by orange-elephant

### Contributor checklist

- [x ] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [ x] I have tested my contribution on these devices:
 * Device A, Android 13
- [x ] My contribution is fully baked and ready to be merged as is
- [x ] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

Payment notes are limited in length to 40 characters, but previously there was absolutely no indication of this, which is very confusing.

This commit adds a simple character counter, and a toast when the EditText is full, to make it clear how much you can write. A missing accessibility description has also been added to the save note button.

<img src="https://user-images.githubusercontent.com/88595467/202564737-645f7188-19fa-4aeb-88c2-c0268ce705f0.jpeg" width="200" />

2022-11-18 16:43 UTC, alex-signal requested changes

2022-11-18 16:43 UTC, alex-signal commented on app/src/main/res/values/strings.xml
> +    <string name="EditNoteFragment__max_note_length_reached">Maximum note length reached</string>
Please add a comment to each of these strings describing what they are used for.

ex.

```
<!-- Note displayed in a toast informing user that max note length has been reached -->
```

Also, this should probably be __maximum_note_length_reached to be consistent with other strings.

2022-11-18 16:43 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/payments/create/EditNoteFragment.java
> +    noteEditText.addTextChangedListener(new TextWatcher() {
We have an `AfterTextChanged` class you can use here.

2022-11-18 16:43 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/payments/create/EditNoteFragment.java
> +    noteEditText.setFilters(new InputFilter[] { new InputFilter.LengthFilter(NOTE_MAX_LENGTH) });
Can we not set this directly in xml?

2022-11-20 22:52 UTC, orange-elephant commented on app/src/main/java/org/thoughtcrime/securesms/payments/create/EditNoteFragment.java
> +    noteEditText.addTextChangedListener(new TextWatcher() {
Thanks!

2022-11-20 22:59 UTC, orange-elephant commented on app/src/main/java/org/thoughtcrime/securesms/payments/create/EditNoteFragment.java
> +    noteEditText.setFilters(new InputFilter[] { new InputFilter.LengthFilter(NOTE_MAX_LENGTH) });
Yeah, the only reason I did this was to have the limit defined in a single place since there is no easy way to get the xml defined value apart from by defining it in a resource integers file or iterating an array of InputFilters. I've now just set this in the XML and the Fragment separately.

2023-01-25 23:18 UTC, dev-aniketj approved these changes

2023-03-27 13:47 UTC, greyson-signal commented
This is in 6.16, thanks :)

2023-03-29 18:21 UTC, closed without merging