Search sticker packs by title in sticker search screen
signalapp/Signal-Android pull request #13554
Opened 2024-05-07 21:11 UTC by spazzylemons

### First time contributor checklist
- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://signal.org/cla/)

### Contributor checklist
- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Pixel 8, Android 14
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

The sticker search screen currently only allows users to search for sticker by their corresponding emoji. This is inconvenient when a sticker you are trying to find does not have an obvious emoji. On Telegram, sticker search shows sticker packs with a matching title first, followed by emoji matches. These changes to the search screen implement this functionality.

Installed sticker packs with a title that partially or fully matches the search query are displayed in full in the search results. After these results, emoji matches are displayed.

Screenshot of the feature:

![image](https://github.com/signalapp/Signal-Android/assets/25674682/514f2e85-65dc-456d-b71a-6f661519eac7)

2024-05-08 12:15 UTC, alex-signal commented
Hi! I'm going to run this by product and see whether they have any concerns.

2024-05-08 12:26 UTC, alex-signal requested changes

2024-05-08 12:26 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/keyboard/sticker/StickerSearchRepository.kt
> +      StickerRecordReader(stickerTable.getStickerPacksByTitle(query)).readAll()
Check out `buildCaseInsensitiveGlob` and its usage.

2024-05-08 14:03 UTC, spazzylemons commented on app/src/main/java/org/thoughtcrime/securesms/keyboard/sticker/StickerSearchViewModel.kt
> +        // This is a sticker. Add directly.
I removed these comments just now.

2024-05-08 14:05 UTC, spazzylemons commented on app/src/main/java/org/thoughtcrime/securesms/keyboard/sticker/StickerSearchRepository.kt
> +      StickerRecordReader(stickerTable.getStickerPacksByTitle(query)).readAll()
I have rewritten getStickerPacksByTitle to create a case-insensitive glob internally, check new StickerTable code [here.](https://github.com/spazzylemons/Signal-Android/blob/main/app/src/main/java/org/thoughtcrime/securesms/database/StickerTable.java#L170)

2024-06-10 20:42 UTC, spazzylemons commented
Any update on this?

2024-08-17 16:14 UTC, closed without merging