Silence ringer with volume buttons
signalapp/Signal-Android pull request #9152
Opened 2019-11-02 11:16 UTC by di72nn

### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [ ] I have tested my contribution on these devices:
 * None
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

Silences incoming call ringer with a volume button press (as in the default Android phone app and many other messenger apps).

That was already implemented for "screen off" event (which is kind of a different use case), I only added handling of volume keys.

I haven't tested it since I don't have an extra Signal account and I don't want to mess with my main account. The change is small, and you'll have to test it yourself anyway. But if you **really** want me to test it first, I guess I can think of something.

Fixes #8338.

2019-11-26 14:54 UTC, Xashyar commented
@di72nn 
Can `android.view.KeyEvent;` event be used for answering calls through Handsfree/Headphone buttons?

2019-11-26 14:54 UTC, Xashyar commented
@di72nn 
Can `android.view.KeyEvent;` be used for answering calls through Handsfree/Headphone buttons?

2019-11-26 21:23 UTC, di72nn commented
@Xashyar 
I'm not sure - it depends on the key code it generates. If it's a "media button" code, see [this guide](https://developer.android.com/guide/topics/media-apps/mediabuttons#foreground-activity), otherwise it indeed should be a simple `KeyEvent`.

2019-12-27 14:09 UTC, di72nn commented
Rebased and tested. Works as expected.

2020-01-11 09:07 UTC, di72nn commented
Rebased again.

2020-01-11 11:46 UTC, nutts0 commented
Could this please be merged. It is an essential feature

2020-04-23 11:33 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/WebRtcCallActivity.java
> +      return true;
This looks like it will silence the ringer whenever vol up or vol down is pressed. There are a couple of problems here:

1. We only want this to be the case when the user sees this activity from their lock screen. 
2. We also only want this to be the case when the call's state matches those within the SILENCE RINGER intent handling.

2. can be solved by using `getStickyEvent` and checking against the event state, as is done in a few other places.

1. might be a trickier solve.

This (only silencing when in 'lock screen' mode) is in line with what other calling apps do. For example, if you enter this screen from the notification bar while your phone is unlocked, the volume buttons would only modify volume (as it does in Signal today).

2020-04-23 11:35 UTC, alex-signal requested changes
![Thank you!](https://media.giphy.com/media/4BylJD2QxStzO/giphy.gif)

Thanks for the PR! And sorry it took a while to get to. I've left some feedback regarding the functionality in another comment.

2020-04-28 20:12 UTC, gtsiolis commented on app/src/main/java/org/thoughtcrime/securesms/WebRtcCallActivity.java
> +      return true;
> We only want this to be the case when the user sees this activity from their lock screen.

@alex-signal are you sure about this? I think most, if not all, calling apps allow you to silence the call, using the volume buttons, when the phone is unlocked and you are seeing the notification or the call activity. 📞 

PS. Thanks for adding this @di72nn!

2020-04-29 11:06 UTC, di72nn commented on app/src/main/java/org/thoughtcrime/securesms/WebRtcCallActivity.java
> +      return true;
>  2. We also only want this to be the case when the call's state matches those within the SILENCE RINGER intent handling.
> 
> 3. can be solved by using `getStickyEvent` and checking against the event state, as is done in a few other places.

Added a condition.



> 1. We only want this to be the case when the user sees this activity from their lock screen.
> 
> This (only silencing when in 'lock screen' mode) is in line with what other calling apps do. For example, if you enter this screen from the notification bar while your phone is unlocked, the volume buttons would only modify volume (as it does in Signal today).

Which apps do that? The default Android dialer silences ringer with volume buttons regardless of the way the call screen becomes visible.
How does the way the screen appears matter anyway?

2020-04-29 12:28 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/WebRtcCallActivity.java
> +      return true;
This is secondary information, but according to one of our designers, Telegram, WhatsApp, and Skype all behave the way we currently do when this screen appears while a user has their phone unlocked. 

The silencing only works if the screen is locked (though Skype is the odd one out, and behaves as Signal does now.)

If I'm incorrect here, please let me know and I'll be more than happy to investigate how these apps operate myself, but design doesn't want to sway from what other major messaging clients are doing here.

2020-04-29 21:39 UTC, Xashyar commented on app/src/main/java/org/thoughtcrime/securesms/WebRtcCallActivity.java
> +      return true;
> The silencing only works if the screen is locked (though Skype is the odd one out, and behaves as Signal does now.)

I think the _immediate_ silencing should work in locked state as well. It's hard to imagine a scenario against this, i.e. the user needing to _incrementally_ lower the volume in the very moment the phone rings.

2020-04-30 12:07 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/WebRtcCallActivity.java
> +      return true;
> I think the immediate silencing should work in locked state as well.

This is what I'm saying, but only in this state. We don't currently do this in Signal which is a mistake. Outside of a locked state, the volume controls should behave as they do now.

2022-01-26 09:12 UTC, Xashyar commented
Still reproducible on the latest Signal-Android.

2022-03-27 10:47 UTC, Xashyar commented
This is unfortunately still reproducible on pre-Android 8.0 devices.

2022-06-29 21:29 UTC, Xashyar commented
This issue is still reproducible on pre-API-26 devices.

2022-06-30 13:18 UTC, cody-signal commented
If this can be rebased and fixed I'll merge it.

2022-08-05 13:57 UTC, cody-signal commented
Please feel free to re-open when fixed. Otherwise, closing.

2022-08-05 13:57 UTC, closed without merging

2024-02-27 14:30 UTC, rajsinghUSA commented
Still can't silence with volume keys

2026-02-28 16:52 UTC, di72nn commented
Rebased and addressed the "silence only in lockscreen mode" comment (at least I think I did - I haven't been able to test it since Signal just doesn't let me request that damn SMS code to log in :face_exhaling: ).

I updated the same branch. Not sure if this PR can be reopened - I certainly can't do it.

2026-03-01 15:47 UTC, wertzuz commented
@cody-signal

2026-03-16 15:10 UTC, tylla commented
@cody-signal Could you eventually take a look at this if it could be merged?

2026-05-04 13:45 UTC, tylla commented
@cody-signal, @alex-signal  As I see, this was closed without merging the commits. Could any of you take a look and merge them?

2026-08-10 11:07 UTC, tylla commented
@cody-signal @alex-signal I don't want to be annoying (yeah, I know I am, really sorry), but pretty-please can you take a look at this PR and see if it can be merged? We are so close to finishing this feature.
Thank you in advance!

2026-10-11 19:50 UTC, tylla commented
@cody-signal I can't reopen this ticket and @di72nn is neither capable, but the needed changes were provided.  Please re-open to be able to make progress.

2026-10-13 14:51 UTC, cody-signal commented
The remote work is gone, so can't reopen. We are hopefully moving to Telecom soon and can get this capability via that.

2026-10-16 07:24 UTC, tylla commented
Sorry @cody-signal I don't really get what you mean by "the remote work is gone"?.
As about the telecom introduction, is there a ticket that follows the move? I couldn't find one.