Memory leaks
signalapp/Signal-Android pull request #9221
Opened 2019-11-24 08:09 UTC by diegoramosb

### First time contributor checklist
- [X] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [X] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist
- [X] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [X] I have tested my contribution on these devices:
 * OnePlus 7 Pro Android 10 
- [X] My contribution is fully baked and ready to be merged as is
- [X] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
As Described in #9220, there are memory leaks in the ConversationActivity. This PR aims to solve the ones that happen when opening and closing the activity. The AsyncTasks created in the initializeSecurity() and saveDraft() methods have implicit references to the activity. By moving the code of these AsyncTasks to separate classes and making weak references to the activity, these references are not created and the memory can be liberated. As seen in the memory profiling below, when the app is put in background, memory can be freed up.
![asdf](https://user-images.githubusercontent.com/18556257/69491709-be470580-0e66-11ea-9be8-102bc9ecbab4.png)

2022-01-28 18:39 UTC, EukalyptusX commented
![Screenshot_20220128-193455](https://user-images.githubusercontent.com/42608576/151603072-ffa96447-fcf3-46b4-8ed1-9b554c1bd617.png)

2022-03-30 09:10 UTC, EukalyptusX commented
Thanks stale bot. But it's still not fixed. I won't let this get closed :-)

This is just ridiculous.

2022-03-30 14:20 UTC, alex-signal requested changes

2022-03-30 14:20 UTC, alex-signal commented on src/org/thoughtcrime/securesms/util/task/InitializeSecurityAsyncTask.java
> +    this.activityWeakReference = activityWeakReference;
Activity and Context are going to be the same object here so no need to capture both, we can simply capture the activity.

2022-03-30 14:20 UTC, alex-signal commented on src/org/thoughtcrime/securesms/util/task/InitializeSecurityAsyncTask.java
> +
extra space

2022-03-30 14:20 UTC, alex-signal commented on src/org/thoughtcrime/securesms/util/task/InitializeSecurityAsyncTask.java
> +
These spaces are unnecessary, all of these should be final, and they should be aligned as per our style:

```
private final boolean                currentIsDefaultSms
private final SettableFuture<Boolean future;
```

2022-03-30 14:20 UTC, alex-signal commented on src/org/thoughtcrime/securesms/util/task/InitializeSecurityAsyncTask.java
> +    Context context = contextWeakReference.get();
alignment:

```
Context   context   = contextWeakReference.get();
Recipient recipient = params[0].resolve()
```

2022-03-30 14:20 UTC, alex-signal commented on src/org/thoughtcrime/securesms/util/task/InitializeSecurityAsyncTask.java
> +    boolean signalEnabled = TextSecurePreferences.isPushRegistered(context);
This could actually be activity.getApplicationContext() instead of storing a weak reference to context.

2022-03-30 14:20 UTC, alex-signal commented on src/org/thoughtcrime/securesms/util/task/InitializeSecurityAsyncTask.java
> +    boolean signalEnabled = TextSecurePreferences.isPushRegistered(context);
Also, if context is null, this will throw a null pointer exception?

2022-03-30 14:20 UTC, alex-signal commented on src/org/thoughtcrime/securesms/util/task/InitializeSecurityAsyncTask.java
> +      activityWeakReference.get().handleSecurityChange(result[0], result[1]);
If the activity is null, this will throw a null pointer exception

2022-03-30 14:20 UTC, alex-signal commented on src/org/thoughtcrime/securesms/util/task/SaveDraftAsyncTask.java
> +  public SaveDraftAsyncTask(WeakReference<Context> contextWeakReference, WeakReference<ConversationActivity> activityWeakReference, Recipient recipient, int thisDistributionType, DraftDatabase.Drafts
Constructors in both classes should have nullability annotations on their parameters.

2022-03-30 14:20 UTC, alex-signal commented on src/org/thoughtcrime/securesms/util/task/SaveDraftAsyncTask.java
> +    this.contextWeakReference = contextWeakReference;
same comment about context, if it's the application context, we can just pass it in as-is. The memory leak would have been due to keeping the activity in memory.

2022-03-30 14:20 UTC, alex-signal commented on src/org/thoughtcrime/securesms/util/task/SaveDraftAsyncTask.java
> +    ThreadDatabase threadDatabase = DatabaseFactory.getThreadDatabase(contextWeakReference.get());
Null pointer exception if the weak reference has been cleared.

2022-03-30 14:20 UTC, alex-signal commented on src/org/thoughtcrime/securesms/util/task/SaveDraftAsyncTask.java
> +      threadDatabase.updateSnippet(threadId, drafts.getSnippet(contextWeakReference.get()),
formatting for method calls on multiple lines:

```
threadDatabase.updateSnippet(threadId,
                             drafts...
```

2022-03-30 14:20 UTC, alex-signal commented on src/org/thoughtcrime/securesms/util/task/InitializeSecurityAsyncTask.java
> +    activityWeakReference.get().onSecurityUpdated();
This strongly couples this task to the activity. Instead, we should create a callback interface which describes what methods this needs, and pass an implementation of it (which can be the activity, or an inner object in the activity)

```
interface Callback {
    void handleSecurityChange(InitializeSecurityAsyncTaskResult)
    void onSecurityUpdated()
}
```

2022-03-30 14:20 UTC, alex-signal commented on src/org/thoughtcrime/securesms/util/task/SaveDraftAsyncTask.java
> +    future.set(result);
Consider the callback pattern mentioned above, instead of this future (the callback would wrap the future and set the result on it.

This will prevent possible leak if the future outlives the activity, since this class can keep a weak reference to the callback.

Just keep in mind that if your callback implementor is an object in the activity and not the activity itself, the activity needs to keep a strong reference to it, otherwise it'll get GC'd and youi'll never invoke it.

2022-07-07 06:34 UTC, closed without merging