Fixes long clicking an item does not update the actionMode title
signalapp/Signal-Android pull request #9701
Opened 2020-06-05 22:42 UTC by fumiakiy

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Essential PH-1, Android 10
 * Virtual device Pixel 2 API 28
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
Adds a call to trigger refreshing the actionMode title to onMediaLongClicked that fixes #9698.

It also moved a set of code from the fragment to the associated ViewModel so the decision around what to show in the action bar could be tested easier. By doing so the code that updates the action bar title is in one place now and whenever an event occurs that may want to update the state of the action bar, they should just call a ViewModel method without worrying about doing other things following a call to the method.

2020-09-14 13:47 UTC, alex-signal requested changes
Could you please also provide screenshots or a video of this change in action?

2020-09-14 13:47 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/mediaoverview/ActionModeTitleData.java
> +  private int mediaCount;
alignment

2020-09-14 13:47 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/mediaoverview/ActionModeTitleData.java
> +    this.mediaCount = mediaCount;
alignment

fields should have `=` alined:

```
this.a  = a;
this.ba = ba;
```

2020-09-14 13:47 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/mediaoverview/MediaOverviewPageFragment.java
> +        detail, sorting, mediaType);
alignment

`adapter` and `detail` should be aligned:

```
method.call(a,
            b);
```

2020-09-14 13:47 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/mediaoverview/MediaOverviewPageFragment.java
> +                                            actionModeTitleData.getMediaCount(),
alignment

2020-09-14 13:47 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/mediaoverview/MediaOverviewPageFragment.java
> +                                            actionModeTitleData.getMediaCount(),
alignment

2020-09-14 13:47 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/mediaoverview/MediaOverviewPageFragment.java
>      FragmentActivity activity = requireActivity();
Probably just cast to `MediaOverviewActivity` here, instead of multiple casts on the next few lines. 

To be fair, I feel as though this should all be part of a single callback/listener call.

2020-09-14 13:47 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/mediaoverview/MediaOverviewPageFragment.java
> +    MediaOverviewPageViewModel pageViewModel = ViewModelProviders.of(this).get(MediaOverviewPageViewModel.class);
move creation to `initializeMediaOverviewPageViewModel` and invoke in `onViewCreated`, storing `pageViewModel` in a class field.

2020-09-14 13:47 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/mediaoverview/MediaOverviewPageViewModel.java
> +  public void updateActionModeTitle(int mediaCount, long selectedMediaSize, boolean isDetailLayout, Sorting sortOrder,
formatting. For methods with multiple params that are multiline, we:

```
public void fun(int a,
                long b)
{
  // body
}
```

2020-09-14 13:47 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/mediaoverview/MediaOverviewPageViewModel.java
> +    actionModeTitleData = new MutableLiveData<>(new ActionModeTitleData(0, 0, false));
inline

2020-09-14 13:47 UTC, alex-signal commented on app/src/test/java/org/thoughtcrime/securesms/mediaoverview/MediaOverviewPageViewModelTest.java
> +public final class MediaOverviewPageViewModelTest {
Always appreciate unit tests!

2020-09-14 19:15 UTC, fumiakiy commented
> Could you please also provide screenshots or a video of this change in action?

Will do and will also respond to the code review. Give me some time.

2020-09-14 22:50 UTC, fumiakiy commented
Thanks for the review! I think I addressed all of the review comments. Please take a look.

2020-09-15 13:59 UTC, alex-signal reviewed
One more small change. Otherwise looks pretty good.

2020-09-15 13:59 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/mediaoverview/MediaOverviewPageFragment.java
> +    super.onViewCreated(view, savedInstanceState);
no need to call super here.

2020-09-15 15:21 UTC, fumiakiy commented
Yes this PR is more than just fixing a bug but attempts to refactor code that is updating action bar title to make it easier to debug and write tests. I understand that it could be considered as a violation to the [Smaller is better](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md#smaller-is-better) part of the contribution guideline.

I'll close this PR because it is going to be significantly different from what it has right now if it focuses only on fixing the bug by the smallest amount of changes.

2020-09-15 15:21 UTC, closed without merging