Use existing content descriptions for call screen. Fixes issue #9774:
signalapp/Signal-Android pull request #9794
Opened 2020-06-26 19:54 UTC by herbig

https://github.com/signalapp/Signal-Android/issues/9774

### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Google Pixel 3a, Android 10
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
This PR fixes #9774 by utilizing existing content description strings on the call screen.  The only complex part is flipping between descriptions for the camera toggle.

There were a few minor bugs I noticed while testing, but thought to limit to fixing just the issue of missing accessibility strings, to keep the PR concise.

2020-06-26 19:56 UTC, herbig commented on app/src/main/res/values/strings.xml
> +    <string name="WebRtcCallControls_video_button_description">Video</string>
Added one additional string.  I'm not yet sure how community translations work, but let me know if there's anything else I need to do to.  We have this string elsewhere, so I could reference that directly here or copy the existing translation for the `WebRtcCallControls_video_button_description` across the `strings.xml` files.

2020-09-14 13:19 UTC, alex-signal requested changes

2020-09-14 13:19 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/components/webrtc/WebRtcCallView.java
> +    final int descYourCam = R.string.WebRtcCallControls_your_camera_button_description;
I feel like we should just have a single "toggle camera" description. Alternatively, the description should be set whenever we know what the local camera state is, instead of changing it here in an on-click, because we could get out of sync otherwise.

2020-09-14 13:19 UTC, alex-signal commented on app/src/main/res/layout/webrtc_call_view.xml
> +            android:contentDescription="@string/WebRtcCallScreen__answer_without_video"
feel free to use auto-layout to properly place these xml attributes, unless that ends up introducing a ton of noise.

2020-09-14 13:19 UTC, alex-signal commented on app/src/main/res/values/strings.xml
> +    <string name="WebRtcCallControls_video_button_description">Video</string>
Nothing else to do here for translations :)

2020-09-17 15:32 UTC, herbig commented on app/src/main/java/org/thoughtcrime/securesms/components/webrtc/WebRtcCallView.java
> +    final int descYourCam = R.string.WebRtcCallControls_your_camera_button_description;
@alex-signal I went the simpler approach, and just added a single description.

2020-09-17 15:33 UTC, herbig commented on app/src/main/res/layout/webrtc_call_view.xml
> +            android:contentDescription="@string/WebRtcCallControls_toggle_camera_description"
The new description used here.

2020-10-19 22:14 UTC, mateuszmp commented on app/src/main/java/org/thoughtcrime/securesms/components/webrtc/WebRtcCallView.java
> +    final int descYourCam = R.string.WebRtcCallControls_your_camera_button_description;
Isn't it possible a blind user might not know if the camera is on or off if there's a singular "toggle camera" description?

2020-10-20 12:07 UTC, alex-signal commented on app/src/main/java/org/thoughtcrime/securesms/components/webrtc/WebRtcCallView.java
> +    final int descYourCam = R.string.WebRtcCallControls_your_camera_button_description;
That's a great point. I'd then opt for the alternative I mentioned.

2022-02-02 02:04 UTC, closed without merging